
----Selects todos
--SELECT * FROM TAB_EMPRESA;

--SELECT * FROM TAB_FORNECEDOR;

--SELECT * FROM TAB_FORNECEDOR_TELEFONE;

--SELECT * FROM TAB_PRODUTO;

--SELECT * FROM TAB_NOTA_FISCAL 

--SELECT * FROM TAB_ITEM_NOTA_FISCAL

--SELECT * FROM TAB_FORNECEDOR_ENDERECO

--SELECT * FROM TAB_FORNECEDOR_ENDERECO

--SELECT * FROM TAB_TELEFONE_EMPRESA;

--SELECT * FROM TAB_TIPO_TELEFONE

--SELECT * FROM TAB_FORNECEDOR_TELEFONE WHERE ID_FORNECEDOR = 13 OR 0 = 13

---- Select Item

--SELECT ID,ID_FORNECEDOR,ENDERECO, BAIRRO, NUMERO, CIDADE, UF, CEP, COMPLEMENTO FROM TAB_FORNECEDOR_ENDERECO WHERE ID = 2;
--SELECT ID,TIPO,ID_FORNECEDOR, TELEFONE FROM TAB_FORNECEDOR_TELEFONE WHERE ID = @ID;


---- Select Inner Join

--SELECT *
-- --TAB_ITEM_NOTA_FISCAL.*,TAB_PRODUTO.* 
-- FROM TAB_ITEM_NOTA_FISCAL  INNER JOIN TAB_NOTA_FISCAL  ON TAB_ITEM_NOTA_FISCAL.ID_NOTA_FISCAL =  TAB_NOTA_FISCAL.ID 
-- where TAB_NOTA_FISCAL.NUMERO =121


--  SELECT TAB_ITEM_NOTA_FISCAL.*,  TAB_PRODUTO.NOME
-- --TAB_ITEM_NOTA_FISCAL.*,TAB_PRODUTO.* 
-- FROM TAB_ITEM_NOTA_FISCAL  INNER JOIN TAB_PRODUTO ON TAB_ITEM_NOTA_FISCAL.ID_PRODUTO =  TAB_PRODUTO.ID 
-- where TAB_PRODUTO.NOME = 'bermuda'



--INSERT INTO TAB_FORNECEDOR_ENDERECO(ID_FORNECEDOR,ENDERECO, BAIRRO, NUMERO, CIDADE, UF, CEP, COMPLEMENTO) 
--VALUES(10, 'fffff', 'ggggg', 45, 'bbbbbb', 'sp', 06720-162, 'fwefwerew')



---- DROP
--ALTER TABLE TAB_NOTA_FISCAL DROP CONSTRAINT FK_ID_RAZAO 
--ALTER TABLE TAB_NOTA_FISCAL DROP COLUMN ID_RAZAO 


----ADD
--ALTER TABLE TAB_NOTA_FISCAL ADD ID_RAZAO INT 

--ALTER TABLE TAB_ITEM_NOTA_FISCAL 
--ADD FOREIGN KEY(ID_PRODUTO) REFERENCES TAB_PRODUTO(ID)

----UPDATE

--UPDATE TAB_NOTA_FISCAL SET ID_RAZAO = 10 WHERE ID = 23

--UPDATE TAB_ITEM_NOTA_FISCAL SET ID_NOTA_FISCAL = 1, 
--ID_PRODUTO = 21, QTDE = 26, VALOR = 50 WHERE ID = 1


----BPK
--SELECT * INTO TAB_NOTA_FISCAL_BKP FROM TAB_NOTA_FISCAL
--SELECT * FROM TAB_NOTA_FISCAL_BKP


----DELETE
--DELETE FROM TAB_EMPRESA WHERE ID = 2

--DELETE FROM TAB_PRODUTO WHERE ID = 13
-- DELETE FROM TAB_FORNECEDOR WHERE ID = 16;
--DELETE FROM TAB_ITEM_NOTA_FISCAL WHERE ID =  1

----INSERT
--INSERT INTO TAB_TELEFONE_EMPRESA(TIPO,ID_EMPRESA, TELEFONE) VALUES(@TIPO,@ID_EMPRESA, @TELEFONE)

--INSERT INTO TAB_NOTA_FISCAL( NUMERO,ID_PRODUTO, VALOR, RAZAO_SOCIAL) 
--                 VALUES(8,1212,12,1);

--INSERT INTO TAB_NOTA_FISCAL( NUMERO,ID_PRODUTO, VALOR, RAZAO_SOCIAL) VALUES(@ID_PRODUTO,@NUMERO,@VALOR,@RAZAO_SOCIAL);

--INSERT INTO TAB_NOTA_FISCAL( NUMERO,ID_PRODUTO, VALOR, RAZAO_SOCIAL) VALUES(@NUMERO, @ID_PRODUTO,@VALOR,@RAZAO_SOCIAL);

--INSERT INTO TAB_ITEM_NOTA_FISCAL(ID_NOTA_FISCAL,ID_PRODUTO, QTDE, VALOR) VALUES (12,22,22,3);

--INSERT INTO TAB_FORNECEDOR_TELEFONE(TIPO,ID_FORNECEDOR, TELEFONE) VALUES(2,13, 11999560823)


----CREATE
--CREATE TABLE TAB_NOTA_FISCA
--(ID INT PRIMARY KEY IDENTITY NOT NULL , NUMERO INT ,VALOR MONEY,RAZAO_SOCIAL VARCHAR(100),ID_PRODUTO INT, 
--CONSTRAINT FK FOREIGN KEY (ID_PRODUTO) REFERENCES TAB_PRODUTO (ID));

--CREATE TABLE TAB_NOTA_FISCA
--(ID INT PRIMARY KEY IDENTITY NOT NULL , NUMERO INT ,VALOR MONEY,RAZAO_SOCIAL VARCHAR(100),ID_PRODUTO INT, 
--CONSTRAINT FK FOREIGN KEY (ID_PRODUTO) REFERENCES TAB_PRODUTO (ID));

--create TABLE TAB_ITEM_NOTA_FISCAL
--(ID INT PRIMARY KEY IDENTITY NOT NULL , QTDE INT ,VALOR MONEY,ID_PRODUTO INT, ID_NOTA_FISCAL INT)

				 
--TAB_FORNECEDOR.ID = TAB_PRODUTO.ID_FORNECEDOR



--SELECT P.NOME as FN ,B.*  FROM TAB_PRODUTO  B INNER JOIN TAB_FORNECEDOR as P ON B.ID_FORNECEDOR = P.ID

                                        
--										--INNER JOIN TAB_NOTA_FISCAL ON TAB_ITEM_NOTA_FISCAL.ID_NOTA_FISCAL =  TAB_NOTA_FISCAL.ID



--SELECT TAB_PRODUTO.NOME,TAB_NOTA_FISCAL.NUMERO,TAB_ITEM_NOTA_FISCAL.* FROM TAB_ITEM_NOTA_FISCAL INNER JOIN TAB_PRODUTO ON TAB_ITEM_NOTA_FISCAL.ID_PRODUTO =  TAB_PRODUTO.ID 
--INNER JOIN TAB_NOTA_FISCAL ON TAB_ITEM_NOTA_FISCAL.ID_NOTA_FISCAL =  TAB_NOTA_FISCAL.ID

--SELECT TAB_PRODUTO.NOME,TAB_ITEM_NOTA_FISCAL.* FROM TAB_ITEM_NOTA_FISCAL INNER JOIN TAB_PRODUTO ON TAB_ITEM_NOTA_FISCAL.ID_PRODUTO =  TAB_PRODUTO.ID
--                                INNER JOIN TAB_NOTA_FISCAL ON TAB_ITEM_NOTA_FISCAL.ID_NOTA_FISCAL =  TAB_NOTA_FISCAL.ID


--SELECT * FROM TAB_NOTA_FISCAL AS NF INNER JOIN TAB_FORNECEDOR AS FO ON ID_RAZAO = FO.ID 
--SELECT * FROM TAB_ITEM_NOTA_FISCAL INNER JOIN TAB_PRODUTO AS FO ON TAB_ITEM_NOTA_FISCAL.ID = ID_PRODUTO WHERE TAB_PRODUTO = FO.NOME
--SELECT NF.ID,NUMERO,ID_PRODUTO, VALOR, FO.RAZAO_SOCIAL FROM TAB_NOTA_FISCAL AS NF 
--                            INNER JOIN TAB_FORNECEDOR AS FO ON ID_RAZAO = FO.ID 
--                           WHERE NUMERO = 1234

--						   SELECT * FROM TAB_NOTA_FISCAL






-- SELECT TAB_PRODUTO.NOME,TAB_ITEM_NOTA_FISCAL.ID,TAB_ITEM_NOTA_FISCAL.ID_NOTA_FISCAL, 
-- TAB_ITEM_NOTA_FISCAL  FROM TAB_ITEM_NOTA_FISCAL INNER JOIN TAB_PRODUTO ON TAB_ITEM_NOTA_FISCAL.ID_PRODUTO =  TAB_PRODUTO.ID
  
  
  
--  SELECT 
-- TAB_ITEM_NOTA_FISCAL.*,TAB_PRODUTO.* 
-- FROM TAB_ITEM_NOTA_FISCAL as d  INNER JOIN TAB_PRODUTO as b ON d.ID_PRODUTO = b.NOME




 
-- SELECT * FROM TAB_ITEM_NOTA_FISCAL AS P INNER JOIN TAB_PRODUTO AS N ON TAB_ITEM_NOTA_FISCAL.ID_PRODUTO =  TAB_PRODUTO.ID 


-- SELECT * FROM TAB_ITEM_NOTA_FISCAL INNER JOIN TAB_PRODUTO AS DD ON  ID_PRODUTO = DD.NOME  

-- SELECT TAB_PRODUTO.NOME,TAB_ITEM_NOTA_FISCAL.ID FROM TAB_ITEM_NOTA_FISCAL INNER JOIN TAB_PRODUTO AS DD ON ID_PRODUTO = DD.NOME

-- SELECT * FROM TAB_ITEM_NOTA_FISCAL INNER JOIN TAB_PRODUTO AS DD ON TAB_ITEM_NOTA_FISCAL.ID_PRODUTO =  TAB_PRODUTO.ID

-- SELECT INF.ID_NOTA_FISCAL,INF.ID_PRODUTO,INF.QTDE, INF.VALOR, PRO.NOME,N.NUMERO  FROM TAB_ITEM_NOTA_FISCAL AS INF INNER JOIN TAB_PRODUTO AS PRO ON INF.ID_PRODUTO = "PRO.NOME" 
-- AND INF.ID_NOTA_FISCAL  = N.NUMERO INNER JOIN TAB_NOTA_FISCAL AS N ON N.NUMERO = INF.ID_NOTA_FISCAL  WHERE PRO.NOME 

-- DELETE FROM TAB_FORNECEDOR WHERE ID = 
-- SELECT * FROM TAB_FORNECEDOR;